services:
  frontend:
    container_name: softvalue-public-next
    image: ghcr.io/fvgtekken/softvault-public-next:latest
    ports:
      - 5001:5001
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - my-network-next-front   
      
networks:
  my-network-next-front:
    external: true
    name: default-network-front